# Generated by Django 4.2.1 on 2023-06-30 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersProfile', '0002_alter_patientprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='adress',
            new_name='address',
        ),
    ]
