# Generated by Django 4.2.1 on 2024-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newletter',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
