# Generated by Django 4.2.1 on 2023-06-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_phone_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
